# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    expose:
      - 80
      - 443
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=true'
      - '--entrypoints.web.address=:80'
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--accesslog=true'
    ports:
      - 80:80
      - 4443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  server:
    build:
      context: .
      dockerfile: Dockerfile.${NODE_ENV:-dev}
    env_file:
      - .env.local
    ports:
      # need it to test oauth
      - 8080:8080
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app.rule=Host(`api.localhost`)'
      - 'traefik.http.routers.app.entrypoints=web'
      - 'traefik.http.routers.app.service=app'
      - 'traefik.http.services.app.loadbalancer.server.port=8080'
      - 'traefik.http.middlewares.app-compress.compress=true'
      - 'traefik.http.middlewares.app-buffer.buffering.maxRequestBodyBytes=10485760'
      - 'traefik.http.middlewares.app-buffer.buffering.memRequestBodyBytes=2097152'
      - 'traefik.http.routers.app.middlewares=app-compress,app-buffer'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      #   - ./dist:/usr/src/app/dist
      - .:/usr/src/app
      - /usr/src/app/node_modules

  redis:
    image: redis:latest
    restart: always
    ports:
      # Warn: This is only exposed for dev purposes
      - 6380:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: postgres:18-alpine
    restart: always
    ports:
      # Warn: This is only exposed for dev purposes
      - 5433:5432
    env_file:
      - .env.local
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
