services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.email=${SSL_EMAIL:-your@email.com}
      - --certificatesresolvers.myresolver.acme.storage=/certs/acme.json
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
    networks:
      - proxy
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/loki.yaml
    expose:
      - 3100
    volumes:
      - ./loki.yaml:/etc/loki/loki.yaml
      - loki-data:/loki
    networks:
      - proxy

  grafana:
    image: grafana/grafana:12.4.1
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN:-localhost}`)'
      - 'traefik.http.routers.grafana.entrypoints=websecure'
      - 'traefik.http.routers.grafana.tls=true'
      - 'traefik.http.routers.grafana.tls.certresolver=myresolver'
      - 'traefik.http.services.grafana.loadbalancer.server.port=3000'
    expose:
      - 3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - proxy

  dbgate:
    image: dbgate/dbgate:alpine
    restart: always
    env_file: .env
    expose:
      - 3000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - dbgate-data:/root/.dbgate
    environment:
      PORT: 3000
      CONNECTIONS: pg,redis
      SKIP_ALL_AUTH: 1

      LABEL_pg: Postgres
      SERVER_pg: db
      USER_pg: ${POSTGRES_USER:-postgres}
      PASSWORD_pg: ${POSTGRES_PASSWORD:-password}
      PORT_pg: 5432
      DATABASE_pg: ${POSTGRES_DB:-postgres}
      ENGINE_pg: postgres@dbgate-plugin-postgres

      LABEL_redis: Redis
      SERVER_redis: redis
      PORT_redis: 6379
      ENGINE_redis: redis@dbgate-plugin-redis
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dbgate.rule=Host(`dbgate.${DOMAIN:-localhost}`)'
      - 'traefik.http.routers.dbgate.entrypoints=websecure'
      - 'traefik.http.routers.dbgate.tls=true'
      - 'traefik.http.routers.dbgate.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.dbgate-auth.basicauth.removeheader=true'
      - 'traefik.http.routers.dbgate.middlewares=dbgate-auth'
      - 'traefik.http.middlewares.dbgate-auth.basicauth.users=${TRAEFIK_DBGATE_USERS}'
      - 'traefik.http.services.dbgate.loadbalancer.server.port=3000'
    networks:
      - proxy

  app_blue:
    image: ${DOCKERHUB_USERNAME:-zakigoumri}/gapzero:latest
    restart: always
    env_file: .env
    networks:
      - proxy
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.myapp.rule=Host(`api.${DOMAIN:-localhost}`)'
      - 'traefik.http.routers.myapp.entrypoints=websecure'
      - 'traefik.http.routers.myapp.tls=true'
      - 'traefik.http.routers.myapp.tls.certresolver=myresolver'
      - 'traefik.http.services.myapp.loadbalancer.server.port=8080'
      - "traefik.http.middlewares.app-compress.compress=true"
      - "traefik.http.middlewares.app-buffer.buffering.maxRequestBodyBytes=10485760"
      - "traefik.http.middlewares.app-buffer.buffering.memRequestBodyBytes=2097152"
      - "traefik.http.routers.app.middlewares=app-compress,app-buffer"
    volumes:
      - ./firebase.config.json:/usr/src/app/firebase.config.json
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8080/health']
      interval: 10s
      timeout: 5s
      retries: 5

  app_green:
    image: ${DOCKERHUB_USERNAME:-zakigoumri}/gapzero:latest
    restart: always
    env_file: .env
    networks:
      - proxy
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.myapp.rule=Host(`api.${DOMAIN:-localhost}`)'
      - 'traefik.http.routers.myapp.entrypoints=websecure'
      - 'traefik.http.routers.myapp.tls=true'
      - 'traefik.http.routers.myapp.tls.certresolver=myresolver'
      - 'traefik.http.services.myapp.loadbalancer.server.port=8080'
      - "traefik.http.middlewares.app-compress.compress=true"
      - "traefik.http.middlewares.app-buffer.buffering.maxRequestBodyBytes=10485760"
      - "traefik.http.middlewares.app-buffer.buffering.memRequestBodyBytes=2097152"
      - "traefik.http.routers.app.middlewares=app-compress,app-buffer"
    volumes:
      - ./firebase.config.json:/usr/src/app/firebase.config.json
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8080/health']
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:18-alpine
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - proxy
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379' ## Expose Redis to test the engine remove this after integratiog with compose internal network
    networks:
      - proxy
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  proxy:
    name: proxy

volumes:
  db-data:
  loki-data:
  grafana-data:
  dbgate-data:
