name: Continuous Deployment

on:
  workflow_run:
    workflows: ['Continuous Integration']
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    name: Blue-Green Deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Infisical CLI
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo bash
          sudo apt-get install -y infisical

      - name: Inject secrets as env vars
        run: |
          infisical export \
            --token=${{ secrets.INFISICAL_TOKEN }} \
            --projectId=${{ secrets.INFISICAL_PROJECT_ID }} \
            --env=production \
            --format=dotenv >> $GITHUB_ENV

      - name: Copy Deploy Scripts to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USERNAME }}
          password: ${{ env.VPS_PASSWORD }}
          source: 'compose.prod.yml,deploy.sh'
          target: '/home/${{ env.VPS_USERNAME }}/zero-waste'

      - name: Export .env from Infisical and copy to VPS
        run: |
          infisical export \
            --token=${{ secrets.INFISICAL_TOKEN }} \
            --projectId=${{ secrets.INFISICAL_PROJECT_ID }} \
            --env=production \
            --format=dotenv > .env

      - name: Copy .env to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USERNAME }}
          password: ${{ env.VPS_PASSWORD }}
          source: '.env'
          target: '/home/${{ env.VPS_USERNAME }}/zero-waste'

      - name: Execute Deployment Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USERNAME }}
          password: ${{ env.VPS_PASSWORD }}
          script: |
            cd /home/${{ env.VPS_USERNAME }}/zero-waste
            chmod +x deploy.sh
            ./deploy.sh
